CREATE DATABASE VETERINARIA

USE VETERINARIA

CREATE TABLE TIPO_MASCOTAS(
	id_tipo_mascota int IDENTITY(1,1) NOT NULL,
	descripcion varchar(50) NULL,
 CONSTRAINT [pk_tipo_mascota] PRIMARY KEY (id_tipo_mascota))

CREATE PROCEDURE PA_TIPO_MASCOTAS
AS
SELECT * FROM TIPO_MASCOTAS

INSERT INTO TIPO_MASCOTAS (descripcion) VALUES ('perro')
INSERT INTO TIPO_MASCOTAS (descripcion) VALUES ('gato')
INSERT INTO TIPO_MASCOTAS (descripcion) VALUES ('araña')
INSERT INTO TIPO_MASCOTAS (descripcion) VALUES ('iguana')
